global using Core.Domain;
global using Core.Responses;
global using Contract.Requests.Shared.Base;
global using Contract.Requests.Courses.CourseRequests;
global using Contract.Requests.Courses.LectureCommentRequests;
global using Contract.Messaging.Models;
global using Contract.BusinessRules.Messaging;
global using Contract.BusinessRules.Validation;
global using MediatR;