name: Build and deploy ASP.Net Core app to Azure Web App - Healpathy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build ".\Gateway\Gateway.csproj" --configuration Release

      - name: dotnet publish
        run: dotnet publish ".\Gateway\Gateway.csproj" -c Release -r win-arm64,win-x64,win-x86 -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DADCFA591B7148B58DF0893AD5A1F3B6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_75325E0DACDC48B5A0A3ABFC330E1C81 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2DCF86B8C84C4A05B18B49D59D4D4ABC }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Healpathy'
          slot-name: 'Production'
          package: .
          